Change workflow to avoid double refs creation

diff --git a/.github/workflows/python-publish.yml b/.github/workflows/python-publish.yml
--- a/.github/workflows/python-publish.yml
+++ b/.github/workflows/python-publish.yml
@@ -8,17 +8,19 @@ on:
 jobs:
   update-version:
     name: Update Version
-    if: "contains(github.event.head_commit.message, 'Bump version')"
+    if: "contains(github.event.push.commits[][message], 'Bump version')"
     runs-on: ubuntu-latest
+    outputs:
+      new_pkg_version: ${{ steps.version.outputs.pkg_version }}
 
     steps:
     - name: Check out repository
       uses: actions/checkout@v4
 
-    - name: Set up Python
+    - name: Set up Python 3.10
       uses: actions/setup-python@v5
       with:
-        python-version: "3.x"
+        python-version: "3.10"
 
     - name: Determine version bump
       id: version
@@ -37,7 +39,7 @@ jobs:
         
         if [[ $new_version ]]; then
           echo "Version bump detected: $new_version"
-          echo "::set-output name=version::$new_version"
+          echo "pkg_version=$new_version" >> $GITHUB_OUTPUT
         else
           echo "No version bump found in the commit messages."
           exit 0
@@ -45,7 +47,7 @@ jobs:
 
     - name: Bump version
       run: |
-        version=${{ steps.version.outputs.version }}
+        version="${{ steps.version.outputs.pkg_version }}"
         if [ -z "$version" ]; then
           echo "No version to bump."
           exit 1
@@ -56,11 +58,16 @@ jobs:
           echo "__version__ = \"$version\"" > docs/version.py
         else
           echo "Updating to version $version"
+          echo "__version__ = \"$version\"" > docs/version.py
         fi
         
         if git diff --quiet; then
           echo "No changes to commit."
           exit 0
+        else
+            git add docs/version.py
+            git commit -m "Bump version to $version"
+            git push origin refs/heads/main
         fi
 
   build:
@@ -70,14 +77,22 @@ jobs:
 
     steps:
     - uses: actions/checkout@v4
-    - name: Set up Python
+    - name: Fetch latest changes
+      run: |
+        git config --global --add safe.directory $GITHUB_WORKSPACE
+        git pull origin main  # Ensure you have the latest commit, including the version bump
+
+    - name: Set up Python 3.10
       uses: actions/setup-python@v5
       with:
-        python-version: "3.x"
+        python-version: "3.10"
+
     - name: Install pypa/build
       run: python3 -m pip install build --user
+
     - name: Build a binary wheel and a source tarball
       run: python3 -m build
+
     - name: Store the distribution packages
       uses: actions/upload-artifact@v4
       with:
@@ -97,12 +112,13 @@ jobs:
         with:
           name: python-package-distributions
           path: dist/
+
       - name: Publish distribution 📦 to PyPI
         uses: pypa/gh-action-pypi-publish@release/v1
 
   github-release:
     name: Sign the Python 🐍 distribution 📦 with Sigstore and upload them to GitHub Release
-    needs: publish-to-pypi
+    needs: [update-version, publish-to-pypi]
     runs-on: ubuntu-latest
     permissions:
       contents: write  # IMPORTANT: mandatory for making GitHub Releases
@@ -114,14 +130,24 @@ jobs:
         with:
           name: python-package-distributions
           path: dist/
+
       - name: Sign the dists with Sigstore
         uses: sigstore/gh-action-sigstore-python@v3.0.0
         with:
           inputs: ./dist/*.tar.gz ./dist/*.whl
+
       - name: Create GitHub Release
         env:
           GITHUB_TOKEN: ${{ github.token }}
-        run: gh release create '${{ github.ref_name }}' --repo '${{ github.repository }}' --notes ""
+          version: ${{needs.update-version.outputs.new_pkg_version}}
+        run: |
+          echo "Creating release for version: $version"
+          if [ -z "$version" ]; then
+            echo "Error: version is not set."
+            exit 1
+          fi
+          gh release create "$version" --repo "${{ github.repository }}" --notes "Release version $version"
+
       - name: Upload artifact signatures to GitHub Release
         env:
           GITHUB_TOKEN: ${{ github.token }}
@@ -146,6 +172,7 @@ jobs:
         with:
           name: python-package-distributions
           path: dist/
+
       - name: Publish distribution 📦 to TestPyPI
         uses: pypa/gh-action-pypi-publish@release/v1
         with:
